# Generated by Django 4.1.7 on 2023-02-22 11:20

from django.db import migrations
from django.db import transaction

class Migration(migrations.Migration):
    def move_data(apps, schema_editor):
        SourceModel = apps.get_model('api', 'Student')
        TargetModel = apps.get_model('api', 'StudentCopy')
        for obj in SourceModel.objects.all():
            target_obj = TargetModel()
            # Set all the necessary fields for the target object
            target_obj.name = obj.name
            target_obj.age = obj.age
            target_obj.department = obj.department
            # Add any other necessary fields and relationships
            with transaction.atomic():
                target_obj.save()

    dependencies = [
        ('api', '0003_auto_20230222_1647'),
    ]

    operations = [
        migrations.RunPython(move_data),
    ]
